Synchronized branch with trunk. Sorry for the huge commit - I tried to merge only the folders I was interested in, but there were too many cross-dependencies.
git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches@930729 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/executioncontext20091231/ant b/executioncontext20091231/ant
--- a/executioncontext20091231/ant
+++ b/executioncontext20091231/ant
@@ -26,13 +26,14 @@ else
 fi
 
 find_jar() {
-	set -- framework/base/lib/ant-launcher-*.jar
-	if [ $# = 1 ] && [ -e "$1" ]; then
-		echo "$1"
-	else
-		echo "Couldn't find ant-launcher.jar" 1>&2
-		exit 1
-	fi
+    top="$(cd "$(dirname "$0")"; echo "$PWD")"
+    set -- "$top"/framework/base/lib/ant-launcher-*.jar
+    if [ $# = 1 ] && [ -e "$1" ]; then
+        echo "$1"
+    else
+        echo "Couldn't find ant-launcher.jar" 1>&2
+        exit 1
+    fi
 }
 "$JAVA" -jar "$(find_jar)" "$@"
 
